benny: .shhtml compiler

metalbeard: static macros for .shhtml
  text-macro: bismuth
  tree-macro: ruthenium

vitruvius: emmet for .shhtml

wildstyle: something to define emmet like stuff (and syntax highlighting) for shhtml compilers

markseid: between .html and .md for hypertext markup